<a href="https://colab.research.google.com/github/SantiAlfonso/Modelo_con_Scikit-learn/blob/main/Modelo_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Objetivos

*   Construir un modelo de regresión lineal que permita estimar el área que podría verse afectada por un incendio forestal.

*   Determinar cuáles son las variables que más inciden en la magnitud de un incendio.

# Instalaer librerías externas

In [86]:
!pip install -U scikit-learn
!pip install statsmodels

Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.9.0)
Requirement already satisfied: numpy>=1.24.1 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (2.0.2)
Requirement already satisfied: scipy>=1.10.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (2.22.1)
Requirement already satisfied: threadpoolctl>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: statsmodels in /usr/local/lib/python3.12/dist-packages (0.14.6)
Requirement already satisfied: numpy<3,>=1.22.3 in /usr/local/lib/python3.12/dist-packages (from statsmodels) (2.0.2)
Requirement already satisfied: scipy!=1.9.2,>=1.8 in /usr/local/lib/python3.12/dist-packages (from statsmodels) (1.16.3)
Requirement already satisfied: pandas!=2.1.0,>=1.4 in /usr/local/lib/python3.12/dist-packages (from statsmodels) (2.2.2)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.12/dist-packages (from statsmodels) (1.0.2)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.12/dist-packages (from statsmodels) (26.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas!=2.1.0,>=1.4->statsmodels) (1.17.0)

# Importar librerías

In [87]:
# Librería para comandos del sistema
import os
# librería para manejo de datos
import pandas as pd
import numpy as np
# Librería para aprendizaje automatico
# Para realizar la separación del conjunto de aprendizaje en entrenamiento y test.
from sklearn.model_selection import train_test_split
# Para conbstruir un modelo con el algoritmo de regresión lineal
from sklearn.linear_model import LinearRegression
# Para determinar el rendimiento del modelo con las métricas MSE, MAE y R2
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
# Para sacar un reporte estadístico que podemos uysar para determinar la importancia de las variables explicativas
import statsmodels.api as sm

# Cargar datos

In [88]:
data = pd.read_excel('incendio_forestal.xlsx')

observamos la cantidad de filas y columnas que posee el dataframe

In [89]:
data.describe()

        area_quemada   Prec_pre_30   Prec_pre_15    Prec_pre_7     Prec_cont
count   37759.000000  37759.000000  37759.000000  37759.000000  37759.000000
mean     2347.020001     35.931177     16.127596      6.764959     21.260950
std     15513.934516    130.257343     65.928608     36.746405     69.377046
min         0.510000      0.000000      0.000000      0.000000      0.000000
25%         1.200000      0.000000      0.000000      0.000000      0.000000
50%         4.000000      0.600000      0.000000      0.000000      0.000000
75%        20.000000     37.900000     12.300000      1.500000      3.300000
max    538049.000000  13560.800000   2527.000000   1638.000000   2126.000000

In [90]:
data.shape

(37759, 8)

In [91]:
data.head()

,area_quemada,clase_incendio,mes_incendio,vegetacion,Prec_pre_30,Prec_pre_15,Prec_pre_7,Prec_cont
0,3.0,B,Diciembre,Desierto polar_roca,59.8,8.4,0.0,86.8
1,60.0,C,Febrero,Bosque tropical perennifolio secundario,168.8,42.2,18.1,124.5
2,1.0,B,Junio,Bosque tropical perennifolio,10.4,7.2,0.0,0.0
3,5.2,B,Enero,Matorral abierto,26.0,0.0,0.0,0.0
4,1.0,B,Noviembre,Matorral abierto,28.4,27.5,1.2,55.4

# Preparamos los datos

Antes de realizar cualquier paso es importante asegurar que estos datos no contienen errores, como datos faltantes, duplicados.

In [92]:
!pip install -U ydata-profiling

Requirement already satisfied: ydata-profiling in /usr/local/lib/python3.12/dist-packages (4.18.4)
Requirement already satisfied: scipy<1.17,>=1.8 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (1.16.3)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.5 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (2.2.2)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (3.10.0)
Requirement already satisfied: pydantic<3,>=2 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (2.12.3)
Requirement already satisfied: PyYAML<6.1,>=6.0.3 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (6.0.3)
Requirement already satisfied: jinja2<3.2,>=3.1.6 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (3.1.6)
Requirement already satisfied: visions<0.8.2,>=0.7.5 in /usr/local/lib/python3.12/dist-packages (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (0.8.1)
Requirement already satisfied: numpy<2.4,>=1.22 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (2.0.2)
Requirement already satisfied: minify-html>=0.15.0 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (0.18.1)
Requirement already satisfied: filetype>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (1.2.0)
Requirement already satisfied: phik<0.13,>=0.12.5 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (0.12.5)
Requirement already satisfied: requests<3,>=2.32.0 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (2.32.4)
Requirement already satisfied: tqdm<5,>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (4.67.3)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (0.13.2)
Requirement already satisfied: multimethod<2,>=1.4 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (1.12)
Requirement already satisfied: statsmodels<1,>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (0.14.6)
Requirement already satisfied: typeguard<5,>=4 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (4.5.2)
Requirement already satisfied: imagehash==4.3.2 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (4.3.2)
Requirement already satisfied: wordcloud>=1.9.4 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (1.9.6)
Requirement already satisfied: dacite<2,>=1.9 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (1.9.2)
Requirement already satisfied: numba<0.63,>=0.60 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (0.60.0)
Requirement already satisfied: PyWavelets in /usr/local/lib/python3.12/dist-packages (from imagehash==4.3.2->ydata-profiling) (1.9.0)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from imagehash==4.3.2->ydata-profiling) (11.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2<3.2,>=3.1.6->ydata-profiling) (3.0.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (26.2)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba<0.63,>=0.60->ydata-profiling) (0.43.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2026.2)
Requirement already satisfied: joblib>=0.14.1 in /usr/local/lib/python3.12/dist-packages (from phik<0.13,>=0.12.5->ydata-profiling) (1.5.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (2026.5.20)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.12/dist-packages (from statsmodels<1,>=0.13.2->ydata-profiling) (1.0.2)
Requirement already satisfied: attrs>=19.3.0 in /usr/local/lib/python3.12/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (26.1.0)
Requirement already satisfied: networkx>=2.4 in /usr/local/lib/python3.12/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (3.6.1)
Requirement already satisfied: puremagic in /usr/local/lib/python3.12/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (2.2.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata-profiling) (1.17.0)

In [93]:
import pandas_profiling
pandas_profiling.ProfileReport(data)

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
100%|██████████| 8/8 [00:00<00:00, 23.69it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

*   En el análisis observamos que tiene 1929 filas duplicadas.
*   Las variables de precipitación tienen una alta correlación entre ellas, lo que puede generar problemas de multicolinealidad.
* También observamos un alto numero de ceros en las variables de precipitaciones

In [94]:
data.shape

(37759, 8)

In [95]:
# Creamos otro dataframe para no trabajar sobre el original
data_t = data.copy()
# 1. Quitamos los duplicados
data_t = data_t.drop_duplicates()
# 2. Nos quedamos solo con la lluvia menos problemática y transformar su sesgo
data_t['Prec_pre_30_log'] = np.log1p(data_t['Prec_pre_30'])
# 3. Eliminar las variables colineales y con exceso de ceros
data_t = data_t.drop(columns=['Prec_pre_15', 'Prec_pre_7', 'Prec_cont', 'Prec_pre_30'])

Tenemos que tener en cuenta que los requerimientos de entrada de los algoritmos de aprendizaje. Para el algoritmo de regresión lineal todas las variables deben ser numéricas, pero en nuestro set de datos poseemos variables categoricas , por lo que se debe realizar una transformación de estas a un formato numerico que se conoce como variables dummies.

In [96]:
# Se muestran las categorías de la variable "clase_incendio" con sus frecuencias
pd.value_counts(data['clase_incendio'])

/tmp/ipykernel_634/3965746002.py:2: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(data['clase_incendio'])

clase_incendio
B    24554
C     7363
G     2997
F     1426
D      954
E      465
Name: count, dtype: int64

In [97]:
# Se muestran las categorías de la variable "mes_incendio" con sus frecuencias
pd.value_counts(data['mes_incendio'])

/tmp/ipykernel_634/3711845707.py:2: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(data['mes_incendio'])

mes_incendio
Marzo         5241
Abril         5003
Julio         4253
Agosto        4087
Junio         3485
Febrero       3130
Mayo          2943
Septiembre    2359
Enero         2156
Octubre       2141
Noviembre     1798
Diciembre     1163
Name: count, dtype: int64

In [98]:
# Se muestran las categorías de la variable "vegetacion" con sus frecuencias
pd.value_counts(data['vegetacion'])

/tmp/ipykernel_634/1451999554.py:2: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(data['vegetacion'])

vegetacion
Matorral abierto                           11949
Bosque tropical perennifolio secundario     8087
Desierto polar_roca                         7510
Bosque tropical perennifolio                6531
Pradera_estepa                              2618
Bosque templado                              619
Desierto                                     445
Name: count, dtype: int64

In [99]:
# Se realiza la transformación de estas variables a dummies.
# Al agregar dtype=int, las columnas nacerán como 1 y 0 numéricos
data_t = pd.get_dummies(data_t, columns=['clase_incendio', 'mes_incendio', 'vegetacion'], drop_first=True, dtype=int)

In [100]:
# Cantidad de datos y número de variables después de esta transformación.
data_t.shape

(26394, 24)

In [101]:
data_t.head()

,area_quemada,Prec_pre_30_log,clase_incendio_C,clase_incendio_D,clase_incendio_E,clase_incendio_F,clase_incendio_G,mes_incendio_Agosto,mes_incendio_Diciembre,mes_incendio_Enero,...,mes_incendio_Mayo,mes_incendio_Noviembre,mes_incendio_Octubre,mes_incendio_Septiembre,vegetacion_Bosque tropical perennifolio,vegetacion_Bosque tropical perennifolio secundario,vegetacion_Desierto,vegetacion_Desierto polar_roca,vegetacion_Matorral abierto,vegetacion_Pradera_estepa
0,3.0,4.107590,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
1,60.0,5.134621,1,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
2,1.0,2.433613,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
3,5.2,3.295837,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,1,0
4,1.0,3.380995,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0

# Construcción del modelo

Los algoritmos supervisados immplementados con la librería scikit-learn requieren que las variables de entrada estén separadas de la variable objetivo. En el casoa de este modelo, la variable objetivo es el "area_quemada".

In [102]:
Y = data_t['area_quemada']
X = data_t.drop(['area_quemada'],axis=1)

In [103]:
X.head()

,Prec_pre_30_log,clase_incendio_C,clase_incendio_D,clase_incendio_E,clase_incendio_F,clase_incendio_G,mes_incendio_Agosto,mes_incendio_Diciembre,mes_incendio_Enero,mes_incendio_Febrero,...,mes_incendio_Mayo,mes_incendio_Noviembre,mes_incendio_Octubre,mes_incendio_Septiembre,vegetacion_Bosque tropical perennifolio,vegetacion_Bosque tropical perennifolio secundario,vegetacion_Desierto,vegetacion_Desierto polar_roca,vegetacion_Matorral abierto,vegetacion_Pradera_estepa
0,4.107590,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,1,0,0
1,5.134621,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,1,0,0,0,0
2,2.433613,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
3,3.295837,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
4,3.380995,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0

In [104]:
Y.head()

0     3.0
1    60.0
2     1.0
3     5.2
4     1.0
Name: area_quemada, dtype: float64

A continuación debemos hacer la separación de nuestros datos en un conjunto para entrenamiento y otro para el test.

El conjunto de entrenamiento se utiliza para ajustar (entrenar) un modelo. Luego, se utiliza el conjunto test para hacer predicciones, las cuales se comparan con los valores esperados para determinar su rendimiento utilizando la métrica seleccionada.

**Train data:** se utiliza para entrenar el modelo con el algoritmo de aprendizaje.

**Test data:** se utiliza para evaluar el ajuste del modelo.

In [105]:
# Se realiza la división entrenamiento - test. Se deja 20% de los datos para el test.
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.2,random_state=0)

Antes de construir el modelo debemos crear un objeto de la clase LinearRegression.

In [106]:
# Primero se crea el objeto para construir el modelo
modelo_regresion = LinearRegression()
# Podemos verificar que lo hemos construido.
modelo_regresion

LinearRegression()

A continuación, procedemos a entrenar el modelo utilizando el conjunto de entrenamiento.

In [107]:
# Ajustar el modelo con los datos de entrenamiento
modelo_regresion.fit(X_train,Y_train)

LinearRegression()

# Evaluamos el modelo

Las metricas de evaluación nos van a permitir determinar qué tan bien se desempeña un modelo; es decir, cómo se ajusta a los datos.

Mean-Squared-Error(MSE). Error medio cuadrático

Mean-Absolute-Error(MAE). Error absoluto medio

R² or Coeficiente de determinación.

In [108]:
y_pred = modelo_regresion.predict(X_train)
# Se obtienen las metricas a partir de la predicción y la base de evaluación (valores reales).
print("-- METRICAS DE ENTRENAMIENTO --")
print("RMSE: %.2f" % np.sqrt(mean_squared_error(Y_train,y_pred)))
print("MAE: %.2f" % mean_absolute_error(Y_train, y_pred))
print('R²: %.2f' % r2_score(Y_train, y_pred))

-- METRICAS DE ENTRENAMIENTO --
RMSE: 15312.18
MAE: 3165.68
R²: 0.23

In [109]:
y_pred = modelo_regresion.predict(X_test)
# Se obtienen las metricas a partir de la predicción y la base de evaluación (valores reales).
print("-- METRICAS DE ENTRENAMIENTO --")
print("RMSE: %.2f" % np.sqrt(mean_squared_error(Y_test,y_pred)))
print("MAE: %.2f" % mean_absolute_error(Y_test, y_pred))
print('R²: %.2f' % r2_score(Y_test, y_pred))

-- METRICAS DE ENTRENAMIENTO --
RMSE: 17240.04
MAE: 3655.67
R²: 0.23

In [110]:
# Ajustar el modelo con los datos de entrenamiento
modelo_regresion.fit(X,Y)

LinearRegression()

In [111]:
# Podemos visualizar los parámetros del modelos (coeficientes de regresión)
modelo_regresion.coef_

array([ -110.14370684,  -102.17669384,  -221.32682054,   187.90782842,
        2986.88449665, 26978.81629396,  -576.51171102,  -206.37409891,
        -278.10877683,  -136.77505163,    85.67805235,  1982.2640867 ,
        -199.38367955,   382.06441132,  -483.23609963,  -242.65504728,
        -717.61886305,  1046.75754591,  -452.68940977, -2424.83149632,
        -643.99898905,  -419.72344444,  -588.56143016])

In [112]:
# Ajustar el modelo para ver el reporte
model = sm.OLS(Y, X).fit() ## sm.OLS(output, input)
# Mostrar las estadísticas del modelo
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results
=======================================================================================
Dep. Variable:           area_quemada   R-squared (uncentered):                   0.254
Model:                            OLS   Adj. R-squared (uncentered):              0.253
Method:                 Least Squares   F-statistic:                              390.6
Date:                Mon, 15 Jun 2026   Prob (F-statistic):                        0.00
Time:                        17:22:17   Log-Likelihood:                     -2.9248e+05
No. Observations:               26394   AIC:                                  5.850e+05
Df Residuals:                   26371   BIC:                                  5.852e+05
Df Model:                          23
Covariance Type:            nonrobust
======================================================================================================================
                                                         coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------------------------------------
Prec_pre_30_log                                      -97.1793     52.422     -1.854      0.064    -199.930       5.572
clase_incendio_C                                     -80.8885    249.597     -0.324      0.746    -570.112     408.334
clase_incendio_D                                    -191.1767    552.971     -0.346      0.730   -1275.031     892.677
clase_incendio_E                                     224.0560    764.714      0.293      0.770   -1274.824    1722.936
clase_incendio_F                                    3027.2511    464.845      6.512      0.000    2116.129    3938.373
clase_incendio_G                                    2.702e+04    356.481     75.784      0.000    2.63e+04    2.77e+04
mes_incendio_Agosto                                 -481.5533    387.915     -1.241      0.214   -1241.887     278.780
mes_incendio_Diciembre                              -130.0019    610.830     -0.213      0.831   -1327.261    1067.258
mes_incendio_Enero                                  -195.8350    523.149     -0.374      0.708   -1221.236     829.566
mes_incendio_Febrero                                 -64.8314    440.199     -0.147      0.883    -927.645     797.982
mes_incendio_Julio                                   177.4189    386.576      0.459      0.646    -580.290     935.128
mes_incendio_Junio                                  2066.3606    416.708      4.959      0.000    1249.590    2883.132
mes_incendio_Marzo                                  -124.9079    372.990     -0.335      0.738    -855.988     606.172
mes_incendio_Mayo                                    471.5802    427.982      1.102      0.271    -367.288    1310.449
mes_incendio_Noviembre                              -402.1168    503.497     -0.799      0.425   -1388.997     584.764
mes_incendio_Octubre                                -158.6970    478.283     -0.332      0.740   -1096.157     778.763
mes_incendio_Septiembre                             -632.3380    456.264     -1.386      0.166   -1526.641     261.965
vegetacion_Bosque tropical perennifolio             1598.8734    380.689      4.200      0.000     852.703    2345.044
vegetacion_Bosque tropical perennifolio secundario   103.3002    365.700      0.282      0.778    -613.492     820.092
vegetacion_Desierto                                -1861.7905    858.208     -2.169      0.030   -3543.924    -179.657
vegetacion_Desierto polar_roca                       -87.0932    351.512     -0.248      0.804    -776.075     601.889
vegetacion_Matorral abierto                          134.8313    350.590      0.385      0.701    -552.344     822.007
vegetacion_Pradera_estepa                            -29.4359    428.825     -0.069      0.945    -869.956     811.084
==============================================================================
Omnibus:                    51448.418   Durbin-Watson:                   1.834
Prob(Omnibus):                  0.000   Jarque-Bera (JB):        132485209.597
Skew:                          15.535   Prob(JB):                         0.00
Kurtosis:                     348.692   Cond. No.                         37.7
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""